In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [27]:
dataset=pd.read_csv('heart_failure_clinical_records_dataset.csv')
dataset

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

In [28]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, 12].values

In [29]:
x

array([[7.500e+01, 0.000e+00, 5.820e+02, ..., 1.000e+00, 0.000e+00,
        4.000e+00],
       [5.500e+01, 0.000e+00, 7.861e+03, ..., 1.000e+00, 0.000e+00,
        6.000e+00],
       [6.500e+01, 0.000e+00, 1.460e+02, ..., 1.000e+00, 1.000e+00,
        7.000e+00],
       ...,
       [4.500e+01, 0.000e+00, 2.060e+03, ..., 0.000e+00, 0.000e+00,
        2.780e+02],
       [4.500e+01, 0.000e+00, 2.413e+03, ..., 1.000e+00, 1.000e+00,
        2.800e+02],
       [5.000e+01, 0.000e+00, 1.960e+02, ..., 1.000e+00, 1.000e+00,
        2.850e+02]])

In [30]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
#splitting data
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
print("shape of x_train", x_train.shape)
print("shape of y_train", y_train.shape)

shape of x_train (224, 12)
shape of y_train (224,)


In [32]:
regressor=LinearRegression()

In [33]:
# fitting simple regression to training set
model=regressor.fit(x_train,y_train)

In [34]:
# coefficient
model.coef_


array([ 6.27086629e-03, -2.87169485e-02,  2.42772539e-05,  4.41206321e-02,
       -8.61983794e-03, -2.11554862e-02, -2.76966817e-07,  8.29812831e-02,
       -6.46765248e-03, -9.21944145e-02,  6.28958406e-02, -2.74785557e-03])

In [35]:
#intercept
model.intercept_

1.496311160003592

In [36]:
#predicting the train results
y_pred=model.predict(x_train)
y_pred

array([ 0.31029678,  0.43992075,  0.74030405,  0.49839808, -0.02315538,
        0.22924345, -0.04121895, -0.01279469,  0.26966102,  0.10622036,
       -0.12933456,  0.6373268 ,  0.41351353,  0.01301839,  0.47975556,
        0.03731602,  0.29442027,  0.04659865,  0.84117562,  0.37116677,
        0.52226833,  1.40498583,  0.29413121,  0.36940915,  0.15656027,
        0.06998711,  0.28815618,  0.10470521,  0.2186686 ,  0.27641171,
       -0.21257909,  0.14672753,  0.47895542,  0.24837331,  0.05568034,
       -0.26433104,  0.36950113, -0.00334116,  0.51947776,  0.22638216,
        0.18095427,  0.59998298,  0.0268831 ,  0.39188181,  0.42403045,
       -0.4401226 ,  0.1419976 ,  0.74121025,  0.41641219,  0.25051916,
        0.03068932,  0.19915546,  0.59184729,  0.08845562,  0.00591311,
        0.00675317,  0.06447938,  0.24445091, -0.07278398,  0.05927526,
        0.16188353,  0.76870177,  0.23716119,  0.56012675,  0.13569078,
        0.05766081,  0.26327495,  1.11205954,  0.69642355,  0.32

In [37]:
#predicting the test set results
y_pred=model.predict(x_test)
y_pred

array([ 0.42766156,  0.57519391,  0.08426414,  0.40036916, -0.04591012,
       -0.16537047,  0.76416956, -0.06574724,  0.23700799,  0.07665726,
        0.21113256,  0.46991694,  0.73455415,  0.44956963,  0.352438  ,
        0.88295071,  0.49765147, -0.24194988,  0.33182927,  0.3559668 ,
        0.37220184,  0.4752317 ,  0.7298002 ,  0.20835784,  0.59828277,
        0.29580781,  0.27574811, -0.08374941,  0.65459288,  0.36752078,
        0.64735538,  0.44993168,  0.10068369,  0.02466627,  0.68770571,
        0.1970814 ,  0.32778498,  0.17453987,  0.70008044, -0.1298286 ,
        0.47599919, -0.07571264,  0.32350359,  0.27012115,  0.53407026,
       -0.1658678 , -0.02530398,  0.17726051,  0.13721235, -0.07553156,
        0.6294454 ,  0.09341481,  0.43739629, -0.01812857,  0.52434243,
        0.28643478,  0.20232367,  0.47587936,  0.0304358 ,  0.67338378,
        0.20710846,  0.52975357,  0.05561375,  0.44631328,  0.37179606,
       -0.00441581,  0.29828135,  0.76837176, -0.09120517,  0.39

In [38]:
# Applying  logistic regression on same data
from sklearn.linear_model import LogisticRegression


In [41]:
model2=LogisticRegression()

In [46]:
# fitting the above data
model2.fit(x_train,y_train)

/home/mukesh/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
model2.classes_

array([0, 1])

In [48]:
#predicting the train data 
model2.predict(x_train)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0])

In [49]:
# predicting probability on train data
model2.predict_proba(x_train)

array([[7.84908204e-01, 2.15091796e-01],
       [6.50288479e-01, 3.49711521e-01],
       [1.71092212e-01, 8.28907788e-01],
       [5.01315437e-01, 4.98684563e-01],
       [9.81120458e-01, 1.88795417e-02],
       [8.18425912e-01, 1.81574088e-01],
       [9.74342922e-01, 2.56570785e-02],
       [9.86934237e-01, 1.30657632e-02],
       [7.06650614e-01, 2.93349386e-01],
       [9.17698416e-01, 8.23015845e-02],
       [9.82394493e-01, 1.76055068e-02],
       [2.39475201e-01, 7.60524799e-01],
       [6.17129108e-01, 3.82870892e-01],
       [9.57578227e-01, 4.24217732e-02],
       [6.41893945e-01, 3.58106055e-01],
       [9.42675063e-01, 5.73249370e-02],
       [7.95848008e-01, 2.04151992e-01],
       [8.96172205e-01, 1.03827795e-01],
       [6.90717687e-02, 9.30928231e-01],
       [7.39744718e-01, 2.60255282e-01],
       [4.16903423e-01, 5.83096577e-01],
       [1.04705130e-01, 8.95294870e-01],
       [6.82953535e-01, 3.17046465e-01],
       [7.73953489e-01, 2.26046511e-01],
       [9.214415

In [50]:
#predicting on the test data
model2.predict(x_test)

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0])

In [51]:
#predicting probability on test data
model2.predict_proba(x_test)

array([[0.66260058, 0.33739942],
       [0.31718283, 0.68281717],
       [0.95388211, 0.04611789],
       [0.63025203, 0.36974797],
       [0.97511649, 0.02488351],
       [0.98941123, 0.01058877],
       [0.42154777, 0.57845223],
       [0.9781696 , 0.0218304 ],
       [0.86783005, 0.13216995],
       [0.92752385, 0.07247615],
       [0.87798633, 0.12201367],
       [0.53103923, 0.46896077],
       [0.12286178, 0.87713822],
       [0.90044122, 0.09955878],
       [0.66346834, 0.33653166],
       [0.23691468, 0.76308532],
       [0.67220834, 0.32779166],
       [0.99638339, 0.00361661],
       [0.74229492, 0.25770508],
       [0.7222777 , 0.2777223 ],
       [0.73775691, 0.26224309],
       [0.48716198, 0.51283802],
       [0.34995188, 0.65004812],
       [0.88657723, 0.11342277],
       [0.47865134, 0.52134866],
       [0.7523318 , 0.2476682 ],
       [0.81588312, 0.18411688],
       [0.93733419, 0.06266581],
       [0.16208717, 0.83791283],
       [0.58683758, 0.41316242],
       [0.